### ISSUE TITLE
疑问？

### ISSUE THREAD

**Issue by yaobo-lab** [schoeu/llog#1]
例如：llog 监控了 hello 这个文件夹的里的日志文件，日志文件夹里有10个日志文件1.log, 2.log,3.log,4.log 等。 有一天llog 重启后，会不会收集这些文件？

**Comment by yaobo-lab** [comment]
好像 也不能在windows 上运行。报错

**Comment by schoeu** [comment]
> 例如：llog 监控了 hello 这个文件夹的里的日志文件，日志文件夹里有10个日志文件1.log, 2.log,3.log,4.log 等。 有一天llog 重启后，会不会收集这些文件？

会的

**Comment by schoeu** [comment]
> 好像 也不能在windows 上运行。报错

可以编译出windows上课运行文件，报错可以贴一下么
